[package]
name = "randl"
version = "0.1.0"
edition = "2024"

[dependencies]
asky = "0.1.1"
clap = { version = "4", features = ["derive"] }
dirs = "6.0.0"
fs2 = "0.4.3"
rand = "0.10.0"
reqwest = { version = "0.12", features = ["blocking"] }
size = "0.5.0"
